--[[
    © 2018 devultj.co.uk, do not share, re-distribute or modify

	without permission of its author (devultj@gmail.com).
]]

dHeists.theme = dHeists.theme or {}

-- Global
dHeists.theme.primaryColor = Color( 45, 45, 45, 255 )
dHeists.theme.secondaryColor = Color( 0, 100, 200, 255 )
dHeists.theme.tertiaryColor = Color( 20, 20, 20, 255 )
dHeists.theme.outlineColor = Color( 180, 180, 180, 2 )

-- Please note that by default, themes are automatically generated by your primary, secondary, tertiary & outline colours.
-- That means it should blend naturally. However, you can change it below if you want!

dHeists.theme.buttonColor = Color( dHeists.theme.primaryColor.r - 10, dHeists.theme.primaryColor.g - 10, dHeists.theme.primaryColor.b - 10, 255 )
dHeists.theme.buttonActiveColor = dHeists.theme.secondaryColor
